blank_issues_enabled: false
contact_links:
  - name: Community Chat (WhatsApp)
    url: https://chat.whatsapp.com/CZblOXj7aV3LMSKCwSUxWR
    about: Ask questions and coordinate with other contributors in our WhatsApp community.
