"""Static analysis of the billing module.

Guards the two controls that would have caught the Apr-Aug 2026 Cloud Run
canary leak: a BigQuery billing export destination, and a budget that alerts on
forecasted as well as actual spend.

Uses the quote-tolerant helpers from conftest rather than positional indexing,
so these tests survive python-hcl2 label-quoting changes.
"""

import os
import pytest

from conftest import (
    find_resource,
    find_variable,
    hcl_str,
    parse_hcl_file,
    resources_of_type,
)


@pytest.fixture(scope="module")
def main_tf(billing_dir):
    path = os.path.join(billing_dir, "main.tf")
    assert os.path.isfile(path), "billing module must declare main.tf"
    return parse_hcl_file(path)


@pytest.fixture(scope="module")
def variables_tf(billing_dir):
    path = os.path.join(billing_dir, "variables.tf")
    assert os.path.isfile(path), "billing module must declare variables.tf"
    return parse_hcl_file(path)


class TestBillingModuleFiles:
    @pytest.mark.parametrize(
        "filename", ["main.tf", "variables.tf", "outputs.tf", "backend.tf", "terragrunt.hcl"]
    )
    def test_file_exists(self, billing_dir, filename):
        assert os.path.isfile(os.path.join(billing_dir, filename))


class TestApiEnablement:
    def test_billingbudgets_api_enabled(self, main_tf):
        svc = find_resource(main_tf, "google_project_service", "billingbudgets")
        assert hcl_str(svc["service"]) == "billingbudgets.googleapis.com"

    def test_bigquery_api_enabled(self, main_tf):
        svc = find_resource(main_tf, "google_project_service", "bigquery")
        assert hcl_str(svc["service"]) == "bigquery.googleapis.com"

    def test_apis_not_disabled_on_destroy(self, main_tf):
        for name, body in resources_of_type(main_tf, "google_project_service").items():
            assert body.get("disable_on_destroy") is False, (
                f"{name}: disabling an API on destroy can break unrelated services"
            )


class TestBillingExportDataset:
    def test_dataset_declared(self, main_tf):
        find_resource(main_tf, "google_bigquery_dataset", "billing_export")

    def test_dataset_id_from_variable(self, main_tf):
        ds = find_resource(main_tf, "google_bigquery_dataset", "billing_export")
        assert "var.billing_export_dataset_id" in str(ds["dataset_id"])

    def test_billing_history_is_not_destroyable(self, main_tf):
        """Billing history is not reproducible; never bulk-delete it on destroy."""
        ds = find_resource(main_tf, "google_bigquery_dataset", "billing_export")
        assert ds.get("delete_contents_on_destroy") is False

    def test_dataset_location_defaults_to_eu(self, variables_tf):
        var = find_variable(variables_tf, "billing_export_location")
        assert hcl_str(var["default"]) == "EU"


class TestBudget:
    def test_budget_declared(self, main_tf):
        find_resource(main_tf, "google_billing_budget", "monthly")

    def test_budget_scoped_to_billing_account(self, main_tf):
        """Account-scoped, not project-scoped: the 2026 leak spanned projects."""
        budget = find_resource(main_tf, "google_billing_budget", "monthly")
        assert "var.billing_account_id" in str(budget["billing_account"])

    def test_budget_uses_monthly_calendar_period(self, main_tf):
        budget = find_resource(main_tf, "google_billing_budget", "monthly")
        assert "MONTH" in str(budget["budget_filter"])

    def test_alerts_on_actual_spend(self, main_tf):
        # Threshold rules are generated by `dynamic` blocks, so assert against
        # the whole budget body rather than a fixed key.
        budget = find_resource(main_tf, "google_billing_budget", "monthly")
        assert "CURRENT_SPEND" in str(budget)

    def test_alerts_on_forecasted_spend(self, main_tf):
        """Forecast alerts arrive with time to react; actual alerts do not."""
        budget = find_resource(main_tf, "google_billing_budget", "monthly")
        assert "FORECASTED_SPEND" in str(budget)

    def test_default_iam_recipients_not_disabled(self, variables_tf):
        """A budget nobody is notified about is not a control."""
        var = find_variable(variables_tf, "budget_disable_default_iam_recipients")
        assert var["default"] is False

    def test_actual_thresholds_include_early_warning(self, variables_tf):
        var = find_variable(variables_tf, "budget_thresholds")
        thresholds = var["default"]
        assert min(thresholds) <= 0.5, "need a threshold at or below 50% to warn early"
        assert 1.0 in thresholds, "need a threshold at 100%"

    def test_forecast_thresholds_non_empty(self, variables_tf):
        var = find_variable(variables_tf, "budget_forecast_thresholds")
        assert len(var["default"]) >= 1


class TestBillingAccountIdValidation:
    def test_billing_account_id_is_validated(self, variables_tf):
        """A typo'd billing account ID should fail at plan, not at apply."""
        var = find_variable(variables_tf, "billing_account_id")
        assert "validation" in var, "billing_account_id must declare a validation block"

    def test_billing_account_id_has_no_default(self, variables_tf):
        var = find_variable(variables_tf, "billing_account_id")
        assert "default" not in var, "billing account must be supplied explicitly"
